GameX/Controllers/EventController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using GameX.DAL;
using GameX.HelperClass;
using GameX.Infrastructure;
using GameX.Models;
using GameX.ViewModel;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;

namespace GameX.Controllers
{
    public class EventController : Controller
    {
        private readonly StoreContext context;
        private IEvent EventManager { get; set; }
        private IEventJoinManager EventJoinManager { get; set; }
        public EventController(StoreContext context)
        {
            this.EventManager = new EventManager(context);
            this.EventJoinManager = new EventJoinManager(context);
            this.context = context;
        }
        public IActionResult Index()
        {
            EventViewModel Model = new EventViewModel();
            Model.Events = context.Events.Include(x => x.EventAdress).ToList();
            return View(Model);
        }
        public IActionResult Add()
        {
            var model = new EventAddressModel();
            model.Address = this.EventManager.getEventsAddress();
            model.Disciplines = this.EventManager.getDisciplines();
            return View(model);
        }

        [HttpPost]
        public IActionResult Add(EventInputModel Event)
        {
            this.EventManager.Add(Event);
            return RedirectToAction("Index");
        }

        public IActionResult Edit(int EventId)
        {

            Events Event = context.Events.Include(x => x.EventAdress).FirstOrDefault(x => x.EventId == EventId);
            EventInputModel model = new EventInputModel()
            {
                Name = Event.Name,
                City = Event.EventAdress.City,
                Street = Event.EventAdress.Street,
                Date = Event.Date,
                HouseNumber = Event.EventAdress.HouseNumber,
                PostCode = Event.EventAdress.PostCode,
                EventId = Event.EventId,
                EventAdressId = Event.EventAdressId,
                Description = Event.Description,
                Disciplines = context.Disciplines.ToList(),
                Address = this.EventManager.getEventsAddress(),
                SelectedDisciplineID = Event.DisciplineId,
                SelectedEventAddressID = Event.EventAdressId,
                Limit = Event.Limit,
            };

            //this.EventManager.Add(Event);
            return View(model);
        }
        public IActionResult Map()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Edit(EventInputModel Event)
        {
            this.EventManager.Edit(Event);
            return RedirectToAction("Index");
            
        }

        [HttpPost]
        public IActionResult Remove(int EventID)
        {
            this.EventManager.Delete(EventID);
            return View();
        }
        [HttpGet]
        public JsonResult getEventsAddress()
        {
            List<CoordAddress> coordAddresses= this.EventManager.getEventsAddress();
            var json = JsonConvert.SerializeObject(coordAddresses);
          
            return Json(new { json} );
        }
        [HttpPost]
        public JsonResult saveEventsCoords(double lat,double lng,int  EventAdressId)
        {
            this.EventManager.SaveCoords(lat, lng, EventAdressId);

            return Json(new { });
        }

        public JsonResult getContent(int EventId)
        {
            MarkerContent content = this.EventManager.GetContent(EventId);
            var json = JsonConvert.SerializeObject(content);
            

            return Json(new { json });
        }
        public JsonResult Join(int EventID,string userID)
        {
            this.EventJoinManager.Join(EventID, userID);


            return Json(new { });
        }

    }
}

GameX/Controllers/LoginController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using GameX.Models;
using GameX.ViewModel;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Options;


using GameX.Services;

namespace GameX.Controllers
{
    [Authorize]

    public class LoginController : Controller
    {
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly SignInManager<ApplicationUser> _signInManager;
        //private readonly IEmailSender _emailSender;
        private readonly ILogger _logger;

        public LoginController(
            UserManager<ApplicationUser> userManager,
            SignInManager<ApplicationUser> signInManager,
            //IEmailSender emailSender,
            ILogger<LoginController> logger)
        {
            _userManager = userManager;
            _signInManager = signInManager;
            //_emailSender = emailSender;
            _logger = logger;
        }
        [HttpGet]
        public async Task<JsonResult> GetCurrentUserId()
        {
            ApplicationUser usr = await GetCurrentUserAsync();
            return  Json(new { ID=usr?.Id });
        }

        private Task<ApplicationUser> GetCurrentUserAsync() => _userManager.GetUserAsync(HttpContext.User);
        [TempData]
        public string ErrorMessage { get; set; }

        [HttpGet]
        [AllowAnonymous]
        public async Task<IActionResult> Login(string returnUrl = null)
        {
         
            // Clear the existing external cookie to ensure a clean login process
            await HttpContext.SignOutAsync(IdentityConstants.ExternalScheme);

            ViewData["ReturnUrl"] = returnUrl;
            return View();
        }

        [HttpPost]
        [AllowAnonymous]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Login(LoginViewModel model, string returnUrl = null)
        {
            ViewData["ReturnUrl"] = returnUrl;
            if (ModelState.IsValid)
            {
                // This doesn't count login failures towards account lockout
                // To enable password failures to trigger account lockout, set lockoutOnFailure: true
                var result = await _signInManager.PasswordSignInAsync(model.Email, model.Password, model.RememberMe, lockoutOnFailure: false);
                if (result.Succeeded)
                {
                    _logger.LogInformation("User logged in.");
                     return RedirectToAction("Index", "MainPage");
                }
                //if (result.RequiresTwoFactor)
                //{
                //    return RedirectToAction(nameof(LoginWith2fa), new { returnUrl, model.RememberMe });
                //}
                if (result.IsLockedOut)
                {
                    _logger.LogWarning("User account locked out.");
                    return RedirectToAction(nameof(Lockout));
                }
                else
                {
                    ModelState.AddModelError(string.Empty, "Invalid login attempt.");
                    return View(model);
                }
            }

            // If we got this far, something failed, redisplay form
            return View(model);
        }

        //[HttpGet]
        //[AllowAnonymous]
        //public async Task<IActionResult> LoginWith2fa(bool rememberMe, string returnUrl = null)
        //{
        //    // Ensure the user has gone through the username & password screen first
        //    var user = await _signInManager.GetTwoFactorAuthenticationUserAsync();

        //    if (user == null)
        //    {
        //        throw new ApplicationException($"Unable to load two-factor authentication user.");
        //    }

        //    var model = new LoginWith2faViewModel { RememberMe = rememberMe };
        //    ViewData["ReturnUrl"] = returnUrl;

        //    return View(model);
        //}

        //[HttpPost]
        //[AllowAnonymous]
        //[ValidateAntiForgeryToken]
        //public async Task<IActionResult> LoginWith2fa(LoginWith2faViewModel model, bool rememberMe, string returnUrl = null)
        //{
        //    if (!ModelState.IsValid)
        //    {
        //        return View(model);
        //    }

        //    var user = await _signInManager.GetTwoFactorAuthenticationUserAsync();
        //    if (user == null)
        //    {
        //        throw new ApplicationException($"Unable to load user with ID '{_userManager.GetUserId(User)}'.");
        //    }

        //    var authenticatorCode = model.TwoFactorCode.Replace(" ", string.Empty).Replace("-", string.Empty);

        //    var result = await _signInManager.TwoFactorAuthenticatorSignInAsync(authenticatorCode, rememberMe, model.RememberMachine);

        //    if (result.Succeeded)
        //    {
        //        _logger.LogInformation("User with ID {UserId} logged in with 2fa.", user.Id);
        //        return RedirectToLocal(returnUrl);
        //    }
        //    else if (result.IsLockedOut)
        //    {
        //        _logger.LogWarning("User with ID {UserId} account locked out.", user.Id);
        //        return RedirectToAction(nameof(Lockout));
        //    }
        //    else
        //    {
        //        _logger.LogWarning("Invalid authenticator code entered for user with ID {UserId}.", user.Id);
        //        ModelState.AddModelError(string.Empty, "Invalid authenticator code.");
        //        return View();
        //    }
        //}

        [HttpGet]
        [AllowAnonymous]
        public async Task<IActionResult> LoginWithRecoveryCode(string returnUrl = null)
        {
            // Ensure the user has gone through the username & password screen first
            var user = await _signInManager.GetTwoFactorAuthenticationUserAsync();
            if (user == null)
            {
                throw new ApplicationException($"Unable to load two-factor authentication user.");
            }

            ViewData["ReturnUrl"] = returnUrl;

            return View();
        }

        [HttpPost]
        [AllowAnonymous]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> LoginWithRecoveryCode(LoginWithRecoveryCodeViewModel model, string returnUrl = null)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            var user = await _signInManager.GetTwoFactorAuthenticationUserAsync();
            if (user == null)
            {
                throw new ApplicationException($"Unable to load two-factor authentication user.");
            }

            var recoveryCode = model.RecoveryCode.Replace(" ", string.Empty);

            var result = await _signInManager.TwoFactorRecoveryCodeSignInAsync(recoveryCode);

            if (result.Succeeded)
            {
                _logger.LogInformation("User with ID {UserId} logged in with a recovery code.", user.Id);
                return RedirectToLocal(returnUrl);
            }
            if (result.IsLockedOut)
            {
                _logger.LogWarning("User with ID {UserId} account locked out.", user.Id);
                return RedirectToAction(nameof(Lockout));
            }
            else
            {
                _logger.LogWarning("Invalid recovery code entered for user with ID {UserId}", user.Id);
                ModelState.AddModelError(string.Empty, "Invalid recovery code entered.");
                return View();
            }
        }

        [HttpGet]
        [AllowAnonymous]
        public IActionResult Lockout()
        {
            return View();
        }

        [HttpGet]
        [AllowAnonymous]
        public IActionResult Register(string returnUrl = null)
        {
            ViewData["ReturnUrl"] = returnUrl;
            return View();
        }

        [HttpPost]
        [AllowAnonymous]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Register(RegisterViewModel model, string returnUrl = null)
        {
            ViewData["ReturnUrl"] = returnUrl;
            if (ModelState.IsValid)
            {
                var user = new ApplicationUser { UserName = model.Email, Email = model.Email };
                var result = await _userManager.CreateAsync(user, model.Password);
                if (result.Succeeded)
                {
                    _logger.LogInformation("User created a new account with password.");

                    var code = await _userManager.GenerateEmailConfirmationTokenAsync(user);
                    var callbackUrl = Url.EmailConfirmationLink(user.Id, code, Request.Scheme);
                    //await _emailSender.SendEmailConfirmationAsync(model.Email, callbackUrl);

                    await _signInManager.SignInAsync(user, isPersistent: false);
                    _logger.LogInformation("User created a new account with password.");
                    return RedirectToAction("Index", "MainPage");
                }
                AddErrors(result);
            }

            // If we got this far, something failed, redisplay form
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Logout()
        {
            await _signInManager.SignOutAsync();
            _logger.LogInformation("Wylogowano.");
            return RedirectToAction("Index", "MainPage");
        }

        //[HttpPost]
        //[AllowAnonymous]
        //[ValidateAntiForgeryToken]
        //public IActionResult ExternalLogin(string provider, string returnUrl = null)
        //{
        //    // Request a redirect to the external login provider.

GameX/Controllers/UserPageController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using GameX.DAL;
using GameX.Infrastructure;
using GameX.Models;
using GameX.ViewModel;
using Microsoft.AspNetCore.Mvc;

namespace GameX.Controllers
{
    public class UserPageController : Controller
    {
        private readonly StoreContext context;
        private IUser UserManager { get; set; }

        public UserPageController(StoreContext context)
        {
            //this.UserManager = new UserManager(context);
            this.context = context;
        }

        public IActionResult UserPage(string UserId)
        {
            Users User = context.Users.FirstOrDefault(x => x.Key == "d4073c9c-117d-462f-a0d9-9e83de6615b0");

            SignUpViewModel model = new SignUpViewModel()
            {
                Email = User.Email,
                Name = User.Name,
                Password = User.Password,
                Surname = User.Surname,
                Username = User.Username,
                UserId = User.UserId
            };

            return View(model);
        }

        [HttpPost]
        public IActionResult UserPage(SignUpViewModel SignUp)
        {
            UserManager.Edit(SignUp);
            return RedirectToAction("../MainPage/Index");
            
            
        }
    }
}

GameX/Views/Shared/_Layout.cshtml
@inject Microsoft.AspNetCore.Identity.SignInManager<ApplicationUser> SignInManager
@inject Microsoft.AspNetCore.Identity.UserManager<ApplicationUser> UserManager

<!DOCTYPE html>
<html>
<head>
    <style>
        .header {
            height: 200px !important;
            /*background-image: url(../images/header-background.jpg);*/
        }
    </style>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - GameX</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
        <link rel="stylesheet" href="~/css/webfonts/fontawesome.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>

    <header class="header header-min">
        <nav class="navigation">
            <div class="navigation__logo"><a asp-area="" asp-controller="MainPage" asp-action="Index">  <img src="~/images/gamex_logo.png" /></a></div>
            <div class="navigation__menuItems">
                <div class="navigation__menuItemes__item">
                    <ul class="navigation__menuItemes__item__mainItem">
                        <li class="navigation__menuItemes__item__mainItem__subMenuItems">
                            <a asp-area="" asp-controller="Event" asp-action="Index">Wydarzenia</a>

                            <ol class="navigation__menuItemes__item__subMenu">
                                <li class="navigation__menuItemes__item__subMenu_item">
                                    <a asp-area="" asp-controller="Event" asp-action="Add">Dodaj</a>
                                </li>

                            </ol>
                        </li>
                    </ul>
                </div>

                <div class="navigation__menuItemes__item"><a>O nas</a></div>
                <div class="navigation__menuItemes__item"><a>Czat</a></div>
                <div class="navigation__menuItemes__item"><a>Kontakt</a></div>
            </div>
            <div class="navigation__menuLogin">
                @if (SignInManager.IsSignedIn(User))
                {
                    <form asp-area="" asp-controller="Login" asp-action="Logout" method="post" id="logoutForm" class="navbar-right">
                        <ul class="nav navbar-nav navbar-right">
                            <li>
                                <a asp-area="" asp-controller="UserPage" asp-action="UserPage" name="d4073c9c-117d-462f-a0d9-9e83de6615b0" title="Manage">Witaj @UserManager.GetUserName(User)! )</a>
                            </li>
                            <li>
                                <button style="color: white; text-decoration: none;" type="submit" class="btn btn-link navbar-btn navbar-link">Wyloguj się</button>
                            </li>
                        </ul>
                    </form>
                }
                else
                {
                    <ul class="nav navbar-nav navbar-right">
                        <li><a asp-area="" asp-controller="Login" asp-action="Register">Zarejestruj się</a></li>
                        <li><a asp-area="" asp-controller="Login" asp-action="Login">Zaloguj się</a></li>
                    </ul>
                }
                @*<a asp-area="" asp-controller="Login" asp-action="Login"><i class="fas fa-user"></i></a>*@
            </div>




        </nav>




    </header>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer class="footerStyle">

            <div class="footerStyle__up">

                <div class="footerStyle__up__note">
                    <h4>O nas</h4>
                    <i class="far fa-address-card"></i>
                    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas rutrum rutrum nibh sit amet efficitur. Aliquam erat volutpat. Sed scelerisque orci elit, ut consequat orci semper ut. Fusce ipsum diam, ultrices a egestas nec, auctor euismod elit.</p>
                </div>

                <div class="footerStyle__up__note">
                    <h4>Kontakt</h4>
                    <i class="far fa-envelope"></i>
                    <p>Praesent non est ut leo fermentum ultricies. Mauris dictum, sapien in rhoncus mattis, felis dui gravida purus, malesuada accumsan mi turpis quis lorem. Praesent aliquet ligula in arcu posuere sagittis. Sed aliquet mauris eu tellus porta vestibulum. Pellentesque tincidunt, odio sed ornare finibus, magna eros posuere leo, vel vestibulum nisi metus at dui. Ut semper ac sem sit amet dapibus. Morbi dapibus dui vel gravida posuere. Mauris a vestibulum arcu, ut commodo enim.</p>
                </div>

                <div class="footerStyle__up__note">
                    <h4>Współpraca</h4>
                    <i class="far fa-comments"></i>
                    <p>Ut in neque urna. Sed venenatis nisi aliquam nisi gravida elementum id a leo. Mauris rhoncus ante nisl, ut posuere arcu convallis sit amet. Nunc eu euismod tortor, a varius turpis. Phasellus magna leo, pellentesque non malesuada sed, efficitur laoreet tortor. Duis sed elementum tortor, a rutrum mi.</p>
                </div>

            </div>
            <div class="footerStyle__down">

                <div class="footerStyle__down__note">
                    <h4>Znajdź nas na mediach społeczznościowych:</h4>
                </div>

                <div class="footerStyle__down__note">
                    <img src="~/images/facebook_icon.png" />
                    <img src="~/images/google_icon.png" />
                    <img src="~/images/twitter_icon.png" />
                    <img src="~/images/email_icon.png" />
                </div>

            </div>

        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>